sudo: true
language: generic
dist: trusty

env:
  global:
    - DOCKER_BASE_TAG=3.7
    - DOCKER_BASE_IMAGE=zeroc/ci-base-ubuntu-16.04:${DOCKER_BASE_TAG}
    - DOCKER_BUILD_IMAGE=zeroc/ci-build-ubuntu-16.04:${TRAVIS_JOB_NUMBER}
    - MAKEFLAGS=OPTIMIZE=no USER_NAMESPACES=no CONFIGS="shared"

jobs:
  include:
    - stage: build docker image
      script:
      - sudo pip install docker-squash
      - cat << EOF > Dockerfile
          FROM ${DOCKER_BASE_IMAGE}
          RUN make ${MAKEFLAGS}
          RUN find cpp/src -name build -exec rm -rf {} + \\
              && find cpp/test -name pie -exec rm -rf {} +
        EOF
      - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
      - docker build --cache-from ${DOCKER_BASE_IMAGE} -t ${DOCKER_BUILD_IMAGE} .
      - docker push ${DOCKER_BUILD_IMAGE}
